version: '3.7'
services:
  anuvaad-corpus-node:
    image: gohila/${image}:${tag}
    deploy:
     replicas: 2
    ports:
    - "8081:8081"
    env_file:
    - ./dev.env
    environment:
      MONGO_URL: ${URL}
    networks:
    - frontend
networks:
  frontend:
    driver: overlay
    external: true    

    
      

    
  
