version: '3.7'
services:
  anuvaad-corpus-node:
    image: gohila/${image}
    deploy:
     replicas: 2
    ports:
    - "8081:8081"
    env_file:
    - ./dev.env
    environment:
      MONGO_URL: ${MONGO_URL}

    
  
